# Generated by Django 3.2.9 on 2022-08-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnailThree',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnailTwo',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='img'),
        ),
    ]
